### ISSUE TITLE
Step In is flakey

### ISSUE THREAD

**Issue by indiejames** [indiejames/vscode-clojure-debug#106]
### Environment
- VSCode Version: 1.8.1
- OS Version: OS X
- Clojure Extension Version: 0.1.0

### Description
Executing a 'step in' at a breakpoint does not go to a source location and I see an exception in the console:

SEVERE: Unhandled REPL handler exception processing message {:frame-index 0, :id EF67014E-B5C9-4E97-B7C0-9B1879C4D73B, :op list-vars, :session 5c08f819-a0eb-4aa7-9276-2ed1da0da793, :thread-name nREPL-worker-1}
java.lang.RuntimeException: No dispatch macro for: '
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:500)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader.read(EdnReader.java:108)
	at clojure.lang.EdnReader.readString(EdnReader.java:64)
	at clojure.edn$read_string.invokeStatic(edn.clj:46)
	at clojure.edn$read_string.invoke(edn.clj:37)
	at cdt.reval$read_preserving_unknown_tags.invokeStatic(reval.clj:323)
	at cdt.reval$read_preserving_unknown_tags.invoke(reval.clj:322)
	at cdt.reval$locals$fn__10357.invoke(reval.clj:340)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6544)
	at clojure.core$reduce.invoke(core.clj:6527)
	at cdt.reval$locals.invokeStatic(reval.clj:333)
	at cdt.reval$locals.invoke(reval.clj:325)
	at debug_middleware.core$eval11671$fn__11673$fn__11675.invoke(core.clj:23)
	at debug_middleware.core$eval11671$fn__11673.invoke(core.clj:22)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at debug_middleware.core$debug_middleware$fn__11838.invoke(core.clj:189)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__986.invoke(interruptible_eval.clj:247)
at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$add_stdin$fn__1067.invoke(session.clj:238)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.pr_values$pr_values$fn__904.invoke(pr_values.clj:22)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn_
<Buffer 5f 37 31 37 2e 69 6e 76 6f 6b 65 28 6d 69 64 64 6c 65 77 61 72 65 2e 63 6c 6a 3a 32 32 29 0a 09 61 74 20 63 6c 6f 6a 75 72 65 2e 74 6f 6f 6c 73 2e 6e ... >
stderr: _717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$session$fn__1052.invoke(session.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.load_file$wrap_load_file$fn__1110.invoke(load_file.clj:79)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__1125.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by indiejames** [comment]
Based on the stack trace this might be related to #101.
