### ISSUE TITLE
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: debug-middleware.core/debug-middleware in this context

### ISSUE THREAD

**Issue by mprokopov** [indiejames/vscode-clojure-debug#138]
### Environment
- VSCode Version: 1.14.2
- OS Version: Mac OS Sierra 10.12.6
- Clojure Extension Version: 1.2.0

### Description
Launch requestListening for transport dt_socket at address: 8030
Custom user.clj loaded.
Error loading debug-middleware.core: java.lang.ClassNotFoundException: com.sun.jdi.Bootstrap, compiling:(cdt/utils.clj:16:1)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: debug-middleware.core/debug-middleware in this context, compiling:(/private/var/folders/g5/1387mml14r7c74rpkgpgcfd40000gn/T/form-init2030913869999407382.clj:1:1524)

### Steps to Reproduce

1. open project https://github.com/indiejames/clojure-code-demo
2. configure clojure.leinPath and clojure.toolsJar properly
3. try to start debugger. Boom.

**Comment by lgazo** [comment]
I have tried it on my project following steps in the manual but with the same result:

Listening for transport dt_socket at address: 9999
Error loading debug-middleware.core: java.lang.ClassNotFoundException: com.sun.jdi.Bootstrap, compiling:(cdt/utils.clj:16:1)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: debug-middleware.core/debug-middleware in this context, compiling:(/tmp/form-init2422059852122939582.clj:1:2629)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6875)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3834)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3834)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6870)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6269)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.analyze(Compiler.java:6625)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:6001)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5380)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3972)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6866)
	at clojure.lang.Compiler.analyze(Compiler.java:6669)
	at clojure.lang.Compiler.eval(Compiler.java:6924)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.eval(Compiler.java:6917)
	at clojure.lang.Compiler.load(Compiler.java:7379)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: debug-middleware.core/debug-middleware in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:710)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6868)

Do you have an idea what might be causing it?
