### ISSUE TITLE
Error when attempting to set breakpoint on un-jarred source file

### ISSUE THREAD

**Issue by indiejames** [indiejames/vscode-clojure-debug#96]
### Environment
- VSCode Version: 1.8.1
- OS Version: OS X
- Clojure Extension Version: 0.1.0

### Description
When attempting to set a breakpoint on an expanded jar file (from a dependency), the operation fails and I see something like the following:

java.lang.Exception: /Users/jnorton/.lein/tmp-vscode-jars/nasa-cmr/cmr-metadata-db-app/0.1.0-SNAPSHOT/cmr-metadata-db-app-0.1.0-SNAPSHOT.jar/cmr/metadata_db/services/provider_service.clj Source not found; check @source-path
	at cdt.break$get_class.invokeStatic(break.clj:143)
	at cdt.break$get_class.invoke(break.clj:138)
	at cdt.break$line_bp.invokeStatic(break.clj:156)
	at cdt.break$line_bp.doInvoke(break.clj:154)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at debug_middleware.jdi$my_set_breakpoint.invokeStatic(jdi.clj:106)
	at debug_middleware.jdi$my_set_breakpoint.invoke(jdi.clj:102)
	at debug_middleware.core$eval11702$fn__11704$fn__11706.invoke(core.clj:58)
	at debug_middleware.core$eval11702$fn__11704.invoke(core.clj:58)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at debug_middleware.core$debug_middleware$fn__11831.invoke(core.clj:182)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__986.invoke(interruptible_eval.clj:247)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$add_stdin$fn__1067.invoke(session.clj:238)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.pr_values$pr_values$fn__904.invoke(pr_values.clj:22)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.load_file$wrap_load_file$fn__1110.invoke(load_file.clj:79)
	at clojure.tools.
<Buffer 6e 72 65 70 6c 2e 6d 69 64 64 6c 65 77 61 72 65 24 77 72 61 70 5f 63 6f 6e 6a 5f 64 65 73 63 72 69 70 74 6f 72 24 66 6e 5f 5f 37 31 37 2e 69 6e 76 6f ... >
stderr: nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.session$session$fn__1052.invoke(session.clj:192)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.server$handle_STAR_.invokeStatic(server.clj:19)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:16)
	at clojure.tools.nrepl.server$handle$fn__1125.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### Steps to Reproduce

1. Create a project with dependencies
2. Jump to definition on a call to a function from one of the dependencies (jar file should be expanded).
3. Attempt to set a breakpoint in the source from the expanded jar file

**Comment by indiejames** [comment]
This was fixed with a previous commit.
